services:
  - type: web
    name: goblin-hut-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: ADMIN_ROLE_ID
        sync: false
      - key: TICKET_WEBHOOK
        sync: false
      - key: SCORE_WEBHOOK
        sync: false
      - key: DATABASE_CHANNEL_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true
