services:
  - type: web
    name: sot-tdm-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0